import { FileText, Download, Calendar, Clock, FileSpreadsheet, File } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useState } from "react";

const reportTemplates = [
  { name: "Monthly Payout Report", description: "Detailed breakdown of all commission payouts for the month.", icon: FileText },
  { name: "Quarterly Summary", description: "Aggregated commission metrics and trends for the quarter.", icon: Calendar },
  { name: "Annual Commission Report", description: "Year-end comprehensive commission analysis and comparisons.", icon: FileSpreadsheet },
  { name: "Department Wise Report", description: "Commission breakdown by department with budget utilization.", icon: File },
  { name: "Employee Wise Report", description: "Individual employee commission earnings and performance.", icon: FileText },
  { name: "Variance Report", description: "Budget vs actual commission variance analysis.", icon: FileSpreadsheet },
  { name: "Audit Report", description: "Commission calculation audit trail and compliance check.", icon: File },
  { name: "Tax Report", description: "TDS and tax deduction summary for commission payouts.", icon: FileText },
];

const recentReports = [
  { name: "Monthly Payout Report - June 2026", generatedBy: "Priya Sharma", date: "2026-07-01", format: "PDF", size: "2.4 MB" },
  { name: "Q2 Quarterly Summary", generatedBy: "Rahul Mehta", date: "2026-07-01", format: "Excel", size: "5.1 MB" },
  { name: "Department Wise - Sales", generatedBy: "System", date: "2026-06-30", format: "PDF", size: "1.8 MB" },
  { name: "Variance Report - June 2026", generatedBy: "Amit Patel", date: "2026-06-28", format: "CSV", size: "890 KB" },
  { name: "Employee Wise - Enterprise Team", generatedBy: "Priya Sharma", date: "2026-06-25", format: "Excel", size: "3.2 MB" },
];

const formatBadgeVariant = (format) => {
  switch (format) {
    case "PDF": return "destructive";
    case "Excel": return "default";
    case "CSV": return "secondary";
    default: return "outline";
  }
};

export default function ReportsPage() {
  const [scheduledEnabled, setScheduledEnabled] = useState(true);

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Reports</h1>
        <p className="text-muted-foreground">Generate and export commission reports</p>
      </div>

      <div>
        <h2 className="text-xl font-semibold mb-4">Report Templates</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {reportTemplates.map((template) => {
            const Icon = template.icon;
            return (
              <Card key={template.name} className="p-5 flex flex-col justify-between">
                <div>
                  <div className="flex items-center gap-3 mb-3">
                    <div className="h-10 w-10 rounded-lg bg-indigo-100 flex items-center justify-center">
                      <Icon className="h-5 w-5 text-indigo-600" />
                    </div>
                    <h3 className="font-semibold text-sm">{template.name}</h3>
                  </div>
                  <p className="text-sm text-muted-foreground mb-4">{template.description}</p>
                </div>
                <Button size="sm" className="w-full">Generate</Button>
              </Card>
            );
          })}
        </div>
      </div>

      <Card className="p-6">
        <h2 className="text-xl font-semibold mb-4">Recent Reports</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Name</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Size</TableHead>
              <TableHead className="text-right">Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {recentReports.map((report) => (
              <TableRow key={report.name}>
                <TableCell className="font-medium">{report.name}</TableCell>
                <TableCell>{report.generatedBy}</TableCell>
                <TableCell>{report.date}</TableCell>
                <TableCell>
                  <Badge variant={formatBadgeVariant(report.format)}>{report.format}</Badge>
                </TableCell>
                <TableCell>{report.size}</TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="sm">
                    <Download className="h-4 w-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>

      <Card className="p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-green-100 flex items-center justify-center">
              <Clock className="h-5 w-5 text-green-600" />
            </div>
            <div>
              <h3 className="font-semibold">Scheduled Report Generation</h3>
              <p className="text-sm text-muted-foreground">Automatically generate and email reports on schedule</p>
            </div>
          </div>
          <button
            onClick={() => setScheduledEnabled(!scheduledEnabled)}
            className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${scheduledEnabled ? "bg-indigo-600" : "bg-gray-200"}`}
          >
            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${scheduledEnabled ? "translate-x-6" : "translate-x-1"}`} />
          </button>
        </div>
        {scheduledEnabled && (
          <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 border-t">
            <div className="flex items-center gap-2 text-sm">
              <Calendar className="h-4 w-4 text-muted-foreground" />
              <span>Monthly Payout Report — 1st of every month</span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Calendar className="h-4 w-4 text-muted-foreground" />
              <span>Quarterly Summary — End of quarter</span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Calendar className="h-4 w-4 text-muted-foreground" />
              <span>Variance Report — Every Friday</span>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}
